In [2]:
import math
import numpy as np
import scipy as sp
from matplotlib import pyplot as plt 
import sys, os 
import time
import csv
%matplotlib inline

In [209]:
nx = ny = 100
A = np.reshape(np.arange(nx * ny),(nx,ny))
print(A)

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


In [199]:
print(np.size(A[0:nx-2, :]))
print(A[nx-(nx-2):, :])
print(A[0:nx-2,:]-A[nx-(nx-2):, :])

15
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[-10 -10 -10 -10 -10]
 [-10 -10 -10 -10 -10]
 [-10 -10 -10 -10 -10]]


In [210]:
print(A[0,:])
print(A[1,:])
print(2*(A[0,:] - A[1,:]))

print(A[nx-2,:])
print(A[nx-1, :])
print(A[nx-2,:] - A[nx-1, :])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]
[-200 -200 -200 -200 -200 -200 -200 -200 -200 -200 -200 -200 -200 -200 -200
 -200 -200 -200 -200 -200 -200 -200 -200 -200 -200 -200 -200 -200 -200 -200
 -200 -200 -200 -200 -200 -200 -200 -200 -200 -200 -200 -200 -200 -200 -200
 -200 -200 -200 -200 -200 -200 -200 -200 -200 -200 -200 -200

In [213]:
Ex = np.zeros([nx, ny])

#internal nodes
Ex[1:nx-1, :] = A[0:nx-2,:]-A[nx-(nx-2):, :]

#boundaries (x=)
#multiply by two so same value as internal nodes
Ex[0,:] = 2* (A[0,:] - A[1,:]) 
Ex[nx-1, :] = 2 * (A[nx-2,:] - A[nx-1, :])

print(Ex)

[[-200. -200. -200. ..., -200. -200. -200.]
 [-200. -200. -200. ..., -200. -200. -200.]
 [-200. -200. -200. ..., -200. -200. -200.]
 ..., 
 [-200. -200. -200. ..., -200. -200. -200.]
 [-200. -200. -200. ..., -200. -200. -200.]
 [-200. -200. -200. ..., -200. -200. -200.]]


In [214]:
print(A[:, 0:ny-2])

[[   0    1    2 ...,   95   96   97]
 [ 100  101  102 ...,  195  196  197]
 [ 200  201  202 ...,  295  296  297]
 ..., 
 [9700 9701 9702 ..., 9795 9796 9797]
 [9800 9801 9802 ..., 9895 9896 9897]
 [9900 9901 9902 ..., 9995 9996 9997]]


In [215]:
print(A[:, 2:ny])

[[   2    3    4 ...,   97   98   99]
 [ 102  103  104 ...,  197  198  199]
 [ 202  203  204 ...,  297  298  299]
 ..., 
 [9702 9703 9704 ..., 9797 9798 9799]
 [9802 9803 9804 ..., 9897 9898 9899]
 [9902 9903 9904 ..., 9997 9998 9999]]


In [216]:
print(A[:, 0:ny-2] - A[:, 2:ny])

[[-2 -2 -2 ..., -2 -2 -2]
 [-2 -2 -2 ..., -2 -2 -2]
 [-2 -2 -2 ..., -2 -2 -2]
 ..., 
 [-2 -2 -2 ..., -2 -2 -2]
 [-2 -2 -2 ..., -2 -2 -2]
 [-2 -2 -2 ..., -2 -2 -2]]


In [217]:
print(A[:, 0])
print(A[:,0]-A[:,1])

print(A[:, ny-1])
print(A[:, ny-2] - A[:, ny-1])

[   0  100  200  300  400  500  600  700  800  900 1000 1100 1200 1300 1400
 1500 1600 1700 1800 1900 2000 2100 2200 2300 2400 2500 2600 2700 2800 2900
 3000 3100 3200 3300 3400 3500 3600 3700 3800 3900 4000 4100 4200 4300 4400
 4500 4600 4700 4800 4900 5000 5100 5200 5300 5400 5500 5600 5700 5800 5900
 6000 6100 6200 6300 6400 6500 6600 6700 6800 6900 7000 7100 7200 7300 7400
 7500 7600 7700 7800 7900 8000 8100 8200 8300 8400 8500 8600 8700 8800 8900
 9000 9100 9200 9300 9400 9500 9600 9700 9800 9900]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[  99  199  299  399  499  599  699  799  899  999 1099 1199 1299 1399 1499
 1599 1699 1799 1899 1999 2099 2199 2299 2399 2499 2599 2699 2799 2899 2999
 3099 3199 3299 3399 3499 3599 3699

In [218]:
Ey = np.zeros([nx, ny])

#internal nodes
Ey[0: ,1:nx-1] = A[:, 0:ny-2] - A[:, 2:ny]

#boundaries (x=0 , nx)
#multiply by two so same value as internal nodes
Ey[:, 0] = 2 * (A[:,0]-A[:,1])
Ey[:,ny-1] = 2 * (A[:, ny-2] - A[:, ny-1])

print(Ey)

[[-2. -2. -2. ..., -2. -2. -2.]
 [-2. -2. -2. ..., -2. -2. -2.]
 [-2. -2. -2. ..., -2. -2. -2.]
 ..., 
 [-2. -2. -2. ..., -2. -2. -2.]
 [-2. -2. -2. ..., -2. -2. -2.]
 [-2. -2. -2. ..., -2. -2. -2.]]


In [10]:
N = 1000 
ny = 10
p_pos = np.zeros([N,2])
np_in = (ny-1) * 15
dh = 0.0074
NP = 2
#x = np.random.rand(np_in,1)
#print(x)
p_pos[NP:NP+np_in, 1: ] = np.random.rand(np_in,1) * dh #x position

print(p_pos[NP:NP+np_in, 1: ])

#while NP < N: 
#    p_pos[NP+1:NP+np_in, 1: ] = np.random.rand(np_in,1) * dh #x position
#    
#    print(p_pos[NP+1:NP+np_in,0])

[[  1.37740911e-03]
 [  3.79940934e-03]
 [  5.95864091e-03]
 [  5.12222157e-04]
 [  2.52843298e-03]
 [  6.80656794e-04]
 [  2.23231931e-04]
 [  6.64052363e-03]
 [  4.62016341e-03]
 [  2.41302205e-03]
 [  3.80873799e-03]
 [  8.07926041e-04]
 [  7.06018016e-03]
 [  3.73279846e-03]
 [  1.47103878e-03]
 [  6.47572357e-03]
 [  5.42456214e-04]
 [  8.11105661e-04]
 [  8.11799619e-04]
 [  2.14075634e-03]
 [  3.56524751e-03]
 [  5.49736998e-03]
 [  2.57123007e-03]
 [  1.01714700e-03]
 [  6.30121035e-03]
 [  6.08158537e-03]
 [  1.71381868e-03]
 [  3.37499863e-03]
 [  3.19126393e-03]
 [  2.05009106e-03]
 [  5.87975065e-07]
 [  5.37366053e-03]
 [  6.47623412e-03]
 [  3.67540288e-04]
 [  2.87019051e-03]
 [  3.12458167e-04]
 [  3.51369400e-03]
 [  3.55658245e-03]
 [  1.88552784e-03]
 [  2.44337392e-03]
 [  6.58873025e-03]
 [  3.18407278e-03]
 [  1.34942200e-03]
 [  3.76689367e-03]
 [  2.74646123e-04]
 [  4.76985147e-03]
 [  3.62798827e-04]
 [  6.98135772e-03]
 [  6.79717425e-03]
 [  3.22198528e-04]


In [207]:
#rho = np.ones((4,4))
#
#x = 100
#y = 100 
#vref = 0
#
#V = np.ones((x,y)) * vref
#
#Te = 1 
#n0 = 1 * 10 ** 12 
#
#source = rho
#nx = np.size(source,1)
#nn = np.size(source)
#
#x0 = np.reshape(source, (nn,1))
#x = x0 - n0 * math.exp(2 * Te)  
#
#
#print(nx,nn, x, type(x), np.size(V))

In [12]:
q = np.zeros((170, 170))

sw = 3683.264706
q_mp = 1
N = 1000
p_pos = np.zeros([N,2])
p_velo = np.zeros([N,2])
dh = 0.006

for p in range (1, N):
    fi = (1 + p_pos[p,0]) / (dh) 
    i = np.floor(fi)
    hx = fi - i
    
    fj = (1 + p_pos[p,1]) / (dh)
    j = np.floor(fj)
    hy = fj - j
    
    q[i,j] = q[i,j] + (1-hx) * (1-hy)
    
rho = (sw + q_mp * q) / (dh * dh)
rho = rho + 1 * 10 ** 4

print(rho)

[[  1.02322908e+08   1.02322908e+08   1.02322908e+08 ...,   1.02322908e+08
    1.02322908e+08   1.02322908e+08]
 [  1.02322908e+08   1.02322908e+08   1.02322908e+08 ...,   1.02322908e+08
    1.02322908e+08   1.02322908e+08]
 [  1.02322908e+08   1.02322908e+08   1.02322908e+08 ...,   1.02322908e+08
    1.02322908e+08   1.02322908e+08]
 ..., 
 [  1.02322908e+08   1.02322908e+08   1.02322908e+08 ...,   1.02322908e+08
    1.02322908e+08   1.02322908e+08]
 [  1.02322908e+08   1.02322908e+08   1.02322908e+08 ...,   1.02322908e+08
    1.02322908e+08   1.02322908e+08]
 [  1.02322908e+08   1.02322908e+08   1.02322908e+08 ...,   1.02322908e+08
    1.02322908e+08   1.02322908e+08]]


/Users/Isabel/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:19: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
